"""Initial migration.

Revision ID: 943a35ec6813
Revises: 
Create Date: 2022-10-05 10:15:55.239687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943a35ec6813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vndr_nm', sa.String(length=120), nullable=False),
    sa.Column('vndr_num', sa.Integer(), nullable=False),
    sa.Column('agmnt_num', sa.Integer(), nullable=False),
    sa.Column('cntrct_stat_cd', sa.String(length=120), nullable=False),
    sa.Column('cntrct_catgy_cd', sa.String(length=120), nullable=False),
    sa.Column('cntrct_eff_dt', sa.Date(), nullable=False),
    sa.Column('cntrct_expir_dt', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agmnt_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    # ### end Alembic commands ###
